import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
// import localFont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tatva Fragrances",
  description: "Generated by create next app",
};
const RedHatDisplay = localFont({
  // Define a CSS variable to use
  variable: "--red-hat-display",
  // Define font weight variants (optional)
  // weight: "font-weight",
  src: [
    { path: "./RedHatDisplay-Regular.woff2" },
    // Add paths for other weights/styles if needed
  ],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={RedHatDisplay.className}>{children}</body>
    </html>
  );
}
